parameters:
  - name: project
    type: string

steps:
  - template: SetupBuildTemplateMain.yml
    parameters:
      project: "${{ parameters.project }}"

  - template: "BuildService.yml"
    parameters:
      project: "${{ parameters.project }}"
