parameters:
  - name: repository
    type: string
  - name: name
    type: string
  - name: tarFilePath
    type: string
  - name: buildId
    type: string

steps:
  - task: Docker@2
    displayName: "Load Image from Tar: ${{ parameters.name }}"
    inputs:
      command: load
      arguments: "--input ${{ parameters.tarFilePath }}/${{ parameters.name }}.image.tar"

  - task: Docker@2
    displayName: "Re-Tag Image to Latest: ${{ parameters.name }}"
    inputs:
      repository: ${{ parameters.repository }}
      command: tag
      arguments: "${{ parameters.repository }}:${{ parameters.buildId }} $(ContainerRegistryName)/${{ parameters.repository }}:latest"

  - task: Docker@2
    displayName: "Re-Tag Image to Version: $(ReleaseVersion)"
    condition: ne(variables.ReleaseVersion, '')
    inputs:
      repository: ${{ parameters.repository }}
      command: tag
      arguments: "${{ parameters.repository }}:${{ parameters.buildId }} $(ContainerRegistryName)/${{ parameters.repository }}:$(ReleaseVersion)"

  - task: Docker@2
    displayName: "Push to ACR: ${{ parameters.name }}"
    inputs:
      command: push
      repository: ${{ parameters.repository }}
      tags: |
        latest
        $(ReleaseVersion)
