parameters:
  - name: project
    type: string

steps:
  - task: UseDotNet@2
    displayName: "Install .NET Core sdk 8.0"
    inputs:
      version: "8.0.403"

  - task: NuGetAuthenticate@1
    displayName: "NuGet Authenticate"

  - task: DotNetCoreCLI@2
    displayName: "NuGet Feed Restore"
    inputs:
      command: "restore"
      projects: "${{ parameters.project }}"
      feedsToUse: "select"
      vstsFeed: "$(dits-nuget-feed)"
